version: 1.2
workflows:
  - name: merge_VCFs
    subclass: WDL
    description: Merge individual sample VCFs to create a unified multi-sample VCF, optionally allowing for modification of sample names.
    primaryDescriptorPath: /workflow.wdl
    authors:
      - name: Shloka Negi
        email: shnegi@ucsc.edu
